/* VitaTrack - données alimentaires de départ. Les valeurs sont indicatives et servent de prototype local. */
const FOOD_DB=[
{name:'Poulet (blanc, cuit)',kcal:165,protein:31,carbs:0,fat:3.6,sugar:0,fiber:0,giLabel:'faible'},
{name:'Œuf entier',kcal:155,protein:13,carbs:1.1,fat:11,sugar:1.1,fiber:0,giLabel:'faible'},
{name:'Riz blanc cuit',kcal:130,protein:2.7,carbs:28,fat:.3,sugar:.1,fiber:.4,giLabel:'élevé'},
{name:'Riz basmati cuit',kcal:130,protein:2.7,carbs:28,fat:.3,sugar:.1,fiber:.4,giLabel:'moyen'},
{name:'Riz complet cuit',kcal:123,protein:2.6,carbs:25.8,fat:1,sugar:.4,fiber:1.6,giLabel:'moyen'},
{name:'Pâtes cuites',kcal:158,protein:5.8,carbs:31,fat:.9,sugar:1.1,fiber:1.8,giLabel:'moyen'},
{name:'Pain complet',kcal:247,protein:9,carbs:41,fat:3.4,sugar:5,fiber:6,giLabel:'moyen'},
{name:'Pain blanc',kcal:265,protein:9,carbs:49,fat:3.2,sugar:5,fiber:2.7,giLabel:'élevé'},
{name:'Avoine (flocons)',kcal:389,protein:16.9,carbs:66,fat:6.9,sugar:1,fiber:10,giLabel:'faible'},
{name:'Banane',kcal:89,protein:1.1,carbs:23,fat:.3,sugar:12,fiber:2.6,giLabel:'moyen'},
{name:'Pomme',kcal:52,protein:.3,carbs:14,fat:.2,sugar:10.4,fiber:2.4,giLabel:'faible'},
{name:'Orange',kcal:47,protein:.9,carbs:12,fat:.1,sugar:9.4,fiber:2.4,giLabel:'faible'},
{name:'Fraises',kcal:32,protein:.7,carbs:7.7,fat:.3,sugar:4.9,fiber:2,giLabel:'faible'},
{name:'Yaourt nature',kcal:61,protein:3.5,carbs:4.7,fat:3.3,sugar:4.7,fiber:0,giLabel:'faible'},
{name:'Fromage blanc 0%',kcal:46,protein:7.5,carbs:4,fat:.2,sugar:4,fiber:0,giLabel:'faible'},
{name:'Skyr nature',kcal:63,protein:11,carbs:4,fat:.2,sugar:4,fiber:0,giLabel:'faible'},
{name:'Lait demi-écrémé',kcal:46,protein:3.3,carbs:4.8,fat:1.6,sugar:4.8,fiber:0,giLabel:'faible'},
{name:'Amandes',kcal:579,protein:21,carbs:22,fat:50,sugar:4.4,fiber:12.5,giLabel:'faible'},
{name:'Beurre de cacahuète',kcal:588,protein:25,carbs:20,fat:50,sugar:9,fiber:6,giLabel:'faible'},
{name:'Saumon (cuit)',kcal:208,protein:20,carbs:0,fat:13,sugar:0,fiber:0,giLabel:'faible'},
{name:'Thon (nature, conserve)',kcal:116,protein:26,carbs:0,fat:1,sugar:0,fiber:0,giLabel:'faible'},
{name:'Bœuf haché 5%',kcal:137,protein:21,carbs:0,fat:5,sugar:0,fiber:0,giLabel:'faible'},
{name:'Lentilles cuites',kcal:116,protein:9,carbs:20,fat:.4,sugar:1.8,fiber:7.9,giLabel:'faible'},
{name:'Pois chiches cuits',kcal:164,protein:8.9,carbs:27,fat:2.6,sugar:4.8,fiber:7.6,giLabel:'faible'},
{name:'Avocat',kcal:160,protein:2,carbs:8.5,fat:14.7,sugar:.7,fiber:6.7,giLabel:'faible'},
{name:'Brocoli (cuit)',kcal:35,protein:2.4,carbs:7,fat:.4,sugar:1.4,fiber:3.3,giLabel:'faible'},
{name:'Courgette cuite',kcal:17,protein:1.2,carbs:3.1,fat:.3,sugar:1.7,fiber:1,giLabel:'faible'},
{name:'Carotte cuite',kcal:35,protein:.8,carbs:8.2,fat:.2,sugar:3.5,fiber:3,giLabel:'moyen'},
{name:'Patate douce (cuite)',kcal:86,protein:1.6,carbs:20,fat:.1,sugar:4.2,fiber:3,giLabel:'moyen'},
{name:'Pomme de terre (cuite)',kcal:87,protein:1.9,carbs:20,fat:.1,sugar:1,fiber:1.8,giLabel:'élevé'},
{name:'Huile d’olive',kcal:884,protein:0,carbs:0,fat:100,sugar:0,fiber:0,giLabel:'faible'},
{name:'Tofu',kcal:76,protein:8,carbs:1.9,fat:4.8,sugar:.6,fiber:.3,giLabel:'faible'},
{name:'Whey (poudre)',kcal:400,protein:80,carbs:8,fat:6,sugar:4,fiber:0,giLabel:'faible'},
{name:'Chocolat noir 70%',kcal:598,protein:7.8,carbs:46,fat:43,sugar:24,fiber:11,giLabel:'faible'},
{name:'Miel',kcal:304,protein:.3,carbs:82,fat:0,sugar:82,fiber:0,giLabel:'élevé'},
{name:'Quinoa cuit',kcal:120,protein:4.4,carbs:21,fat:1.9,sugar:.9,fiber:2.8,giLabel:'faible'},
{name:'Pizza margherita',kcal:250,protein:11,carbs:30,fat:9,sugar:3,fiber:2,giLabel:'moyen'},
{name:'Frites',kcal:312,protein:3.4,carbs:41,fat:15,sugar:.3,fiber:3.8,giLabel:'élevé'},
{name:'Nutella',kcal:539,protein:6.3,carbs:57.5,fat:30.9,sugar:56.3,fiber:0,giLabel:'élevé'}
];
function defaultData(){return{profile:{name:'',age:0,sex:'homme',height:0,weightCurrent:0,startingWeight:0,activity:'moderate',dailyActivity:'moderate',sportSessionsPerWeek:0,bodyFat:null,waist:null,visceralFat:null},objective:{type:'fat_loss',targetWeight:null,targetBodyFat:null,targetWaist:null,pace:'coach'},nutrition:{caloriesTarget:null,proteinTarget:null,manualCalories:false,manualProtein:false,waterTarget:2},sport:{profile:{level:'debutant',sessionsPerWeek:3,sessionDuration:35,equipment:['aucun'],preferredDays:['lun','mer','ven'],objectives:[]},objectives:{primary:'condition_physique',secondary:[]},currentProgram:null,sessionHistory:[],exerciseProgress:{},monthlyChallenge:null,coachDecisions:[],constraints:[]},settings:{theme:'light'},foodLog:{},weights:[],customFoods:[],coachDecisions:[],reports:{},stepsLog:{}};}
